wandb_version: 1

optimizer:
  desc: null
  value: Adam
architecture:
  desc: null
  value: Efficientnet B0
dataset:
  desc: null
  value: Food101
epochs:
  desc: null
  value: 49
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698747489.560302
    t:
      1:
      - 1
      - 11
      - 35
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 35
      - 41
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      6: 4.33.1
      8:
      - 5
      13: linux-x86_64
